#Dev config

#vscode
install_code=true 

#extension for vscode
install_python_extension_for_vscode=true
install_c_extension_for_vscode=true
install_run_extension_for_vscode=true

#python
install_python3=true

#NodeJS
install_nodejs=true

#CTF config

#ghidra
install_ghidra=true 

#wordlist
install_wordlist=true 

#Wireshark
install_wireshark=true
