#Dev config

#Chromium
install_chromium=true

#vscode
install_code=true 

#git
install_git=true

#extension for vscode
install_python_extension_for_vscode=true
install_c_extension_for_vscode=true
install_run_extension_for_vscode=true

#python
install_python3=true

#NodeJS
install_nodejs=true
